table Customers
	lineageTag: 3633b790-c4c0-4ee7-a2aa-3575b66f4ad0

	measure rankrow = RANKX(ALL(Customers[Customer Name],Customers[Customer ID]),[Total_sales],,DESC)
		formatString: 0
		lineageTag: a06958db-72d6-4d38-9fec-770751dcbea4

	measure DynamicRanking = ```
			
			IF(
			    SELECTEDVALUE(TOPBOTTOM[Value])="Top",
			    RANKX(ALLSELECTED(Customers[Customer Name]),[Total_sales],,DESC,Dense),
			    
			    RANKX(ALLSELECTED(Customers[Customer Name]),[Total_sales],,ASC,Dense)
			)
			```
		formatString: 0
		lineageTag: 20710c63-27b4-4b21-9603-92e9e5cb568a

	measure condition = if([DynamicRanking]<=parameter[parameter Value],1,0)
		formatString: 0
		lineageTag: a4dc6d20-2a8a-42c7-b884-63f0dc98be49

	measure 'Rank by Sales' = RANKX(ALLSELECTED(Customers[Customer Name]),[Total_sales],,DESC)
		formatString: 0
		lineageTag: 97b33706-4256-4ef4-8099-63b7661a07d2

	measure 'Selected TopN' = ```
			
			SELECTEDVALUE('TopN Selector'[TopN])
			
			
			```
		formatString: 0
		lineageTag: 4ecb209d-b7aa-4e77-a1ee-720da71a7b17

	measure 'Show TopN' = ```
			
			VAR ABCD = [Selected TopN]
			RETURN
			IF(
			    ISBLANK(ABCD),                
			    1,                         
			    IF([Rank by Sales] <= ABCD, 1, 0)
			)
			
			```
		formatString: 0
		lineageTag: caf310b9-fadf-4027-8ac1-8eb70ec69415

	measure Dynamic_Title =
			
			var _Multiplevalues= CONCATENATEX(DISTINCT(Customers[Customer Name]),Customers[Customer Name],",  ")
			var ABCD=
			if (
			                        ISFILTERED(Customers[Customer Name]), "Average Sales by " & SELECTEDVALUE(Customers[Customer Name],_Multiplevalues))
			
			
			                        RETURN
			
			                        ABCD
		lineageTag: ad5375dd-2a25-4e30-8e6e-9ab851e77625

	column 'Customer ID'
		dataType: string
		lineageTag: 7a71afa7-117b-48b5-aa3f-d42b9a901bf1
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 4bb5d9e4-d05a-4cdc-b7a7-13ea198c31b4
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: f5de6bee-6f30-4e14-af29-66bab2d39dc4
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: 4bfa1149-5c95-4dcc-b2ed-35141ad2c441
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Phone
		dataType: string
		lineageTag: f8946da7-3a12-4668-8b60-d217e45c2ca8
		summarizeBy: none
		sourceColumn: Phone

		annotation SummarizationSetBy = Automatic

	column 'Join Date'
		dataType: int64
		formatString: 0
		lineageTag: 4d1b39ee-8e0e-4570-9152-8afc75ae69b8
		summarizeBy: none
		sourceColumn: Join Date

		annotation SummarizationSetBy = Automatic

	column rank = if(RANKX(Customers,[Total_sales],,DESC,Dense)<4, Customers[Customer Name])
		lineageTag: 698c113b-942d-4834-b0fc-15e6b868e14a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ranktest = RANKX(Customers,Sales[Total_sales],,ASC)
		formatString: 0
		lineageTag: f2504149-53fc-4f16-b40d-e90f0dccc970
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Customers = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\10849622\Downloads\customer_sales_sample.xlsx"), null, true),
				    Customers_Sheet = Source{[Item="Customers",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Customers_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Customer ID", type text}, {"Customer Name", type text}, {"Region", type text}, {"Email", type text}, {"Phone", type text}, {"Join Date", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

