table TOPBOTTOM
	lineageTag: 1135b74e-f3e4-4a83-837f-a31bc06d6d3d

	column Value
		dataType: string
		lineageTag: 7dfc1ca1-9b66-49bd-91c2-9456ba601ea7
		summarizeBy: none
		sourceColumn: Value
		sortByColumn: Sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Sort
		dataType: int64
		formatString: 0
		lineageTag: 14c056d6-5b58-4010-b227-fce306a5e709
		summarizeBy: sum
		sourceColumn: Sort

		annotation SummarizationSetBy = Automatic

	partition TOPBOTTOM = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCskvUNJRMlSK1YlWcsovKcnPBXKNlGJjAQ==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Value = _t, Sort = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Value", type text}, {"Sort", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

